---
# Global variables for tutor-k3s-ansible

# Path settings
tfgrid_dir: "{{ playbook_dir }}/../../tfgrid-k3s"
project_root: "{{ playbook_dir | dirname }}"

# K8s configuration
k8s_config_dir: "{{ project_root }}/config"
kubeconfig_path: "{{ k8s_config_dir }}/k3s.yaml"
project_dir: "{{ playbook_dir }}"
venv_dir: "{{ project_dir }}/venv"

# Kubernetes settings
openedx_namespace: "openedx"
min_file_descriptors: 1048576

# Docker Hub credentials
# These can be overridden via environment variables or in host_vars
docker_username: "{{ lookup('env', 'DOCKER_USERNAME') | default('') }}"
docker_token: "{{ lookup('env', 'DOCKER_TOKEN') | default('') }}"
docker_email: "{{ lookup('env', 'DOCKER_EMAIL') | default('') }}"

# Tutor settings
lms_host: "lms.local"
cms_host: "studio.local"

# Deployment settings
max_retries: 30
retry_interval: 10  # seconds

# Resource management settings
resource_limits:
  lms:
    cpu: "2"
    memory: "2Gi"
  cms:
    cpu: "2"
    memory: "2Gi"
  mysql:
    cpu: "1"
    memory: "1Gi"
  mongodb:
    cpu: "1"
    memory: "1Gi"
  elasticsearch:
    cpu: "1"
    memory: "2Gi"
  redis:
    cpu: "0.5"
    memory: "512Mi"

# Longhorn storage settings
longhorn_replica_count: 2  # Number of replicas for volumes
longhorn_enable_snapshots: true