---
# Main playbook for tutor-k3s-ansible

- name: Set up and deploy Open edX on K3s
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  tasks:
    - name: Include common variables
      include_vars: group_vars/all.yml
