---
# Cleanup playbook - runs the cleanup role

- name: Clean up stuck pods
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  tasks:
    - name: Include common variables
      include_vars: ../group_vars/all.yml
      
    - name: Run cleanup role
      include_role:
        name: cleanup
