---
# Prepare playbook - runs the prepare role

- name: Prepare Kubernetes for Tutor
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  tasks:
    - name: Include common variables
      include_vars: ../group_vars/all.yml
    
    - name: Set Python interpreter
      set_fact:
        ansible_python_interpreter: "{{ venv_dir }}/bin/python3"
        
    - name: Set explicit kubeconfig path
      set_fact:
        kubeconfig: "{{ kubeconfig_path }}"
      
    - name: Show kubeconfig path
      debug:
        msg: "Using kubeconfig: {{ kubeconfig }}"
      
    - name: Run prepare role
      include_role:
        name: prepare
