---
# Registry auth playbook - runs the registry role

- name: Configure Docker Registry Authentication
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  tasks:
    - name: Include common variables
      include_vars: ../group_vars/all.yml
    
    - name: Set Python interpreter
      set_fact:
        ansible_python_interpreter: "{{ venv_dir }}/bin/python3"
      
    - name: Run registry role
      include_role:
        name: registry
