---
# Setup storage playbook - runs the longhorn role to provision reliable storage

- name: Set up Longhorn storage for OpenedX
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  pre_tasks:
    - name: Include common variables
      include_vars: ../group_vars/all.yml
    
    - name: Set Python interpreter
      set_fact:
        ansible_python_interpreter: "{{ venv_dir }}/bin/python3"
        
    - name: Set explicit kubeconfig path
      set_fact:
        kubeconfig: "{{ kubeconfig_path }}"
      
    - name: Show kubeconfig path
      debug:
        msg: "Using kubeconfig: {{ kubeconfig }}"
        
    - name: Ensure kubectl is available
      ansible.builtin.command: which kubectl
      register: kubectl_check
      ignore_errors: true
      changed_when: false
  
    - name: Wait for K3s API server to be fully ready before proceeding
      ansible.builtin.shell: |
        echo "Performing comprehensive K3s API server readiness check..."
        
        # Try to get nodes multiple times with increasing timeout
        attempts=0
        max_attempts=15
        
        for attempt in $(seq 1 $max_attempts); do
          echo "Attempt $attempt/$max_attempts - Testing API server connectivity..."
          
          if kubectl get nodes --request-timeout=20s > /dev/null 2>&1; then
            echo "API server responded successfully!"
            
            # Now check if core components are ready
            echo "Checking core system components..."
            
            # Check if kube-system pods are mostly running
            RUNNING_PODS=$(kubectl get pods -n kube-system --field-selector=status.phase=Running 2>/dev/null | grep -c Running || echo 0)
            if [ $RUNNING_PODS -lt 2 ]; then
              echo "Warning: Less than 2 pods running in kube-system namespace. K3s may still be initializing."
              echo "Waiting 20 seconds before next attempt..."
              sleep 20
              continue
            fi
            
            # API server is responsive and core components are running
            echo "K3s API server is fully ready."
            exit 0
          else
            echo "API server not responding. Waiting 20 seconds before next attempt..."
            sleep 20
          fi
        done
        
        echo "ERROR: K3s API server not ready after $max_attempts attempts"
        exit 1
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
      register: k3s_ready
      retries: 2
      delay: 5
      until: k3s_ready.rc == 0
      changed_when: false
      
    - name: Display K3s status
      debug:
        msg: "{{ k3s_ready.stdout_lines }}"
  
  tasks:
    - name: Install and configure Longhorn
      include_role:
        name: longhorn
      when: k3s_ready.rc == 0
      
    - name: Display completion message
      debug:
        msg: |
          Storage setup process completed.
          {% if k3s_ready.rc == 0 %}
          Longhorn storage has been configured.
          
          Now you can deploy OpenedX with reliable storage by running:
          make deploy
          
          Your deployment will have high-availability persistent storage.
          {% else %}
          WARNING: K3s API server was not ready. Storage setup may not be complete.
          
          You may need to retry the setup-storage step after the cluster is fully initialized:
          make setup-storage
          {% endif %}