---
# Setup playbook - runs the setup role

- name: Set up Tutor for K3s
  hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  
  tasks:
    - name: Include common variables
      include_vars: ../group_vars/all.yml
      
    - name: Run setup role
      include_role:
        name: setup
